import { useMemo, useState } from "react";
import PageIcon from "./PageIcon";

const collections = [
  { id: "getting-started", label: "Getting started", count: 8, icon: "sparkles" },
  { id: "workspace", label: "Workspace & projects", count: 14, icon: "layers" },
  { id: "account", label: "Account & billing", count: 11, icon: "creditCard" },
  { id: "security", label: "Security & privacy", count: 9, icon: "lock" },
  { id: "integrations", label: "Integrations", count: 7, icon: "code" },
];

const articles = [
  { id: "invite-team", collection: "getting-started", type: "Guide", title: "Invite your team and set up roles", excerpt: "Bring teammates into your workspace and choose the right access level for every role.", read: "4 min read", updated: "Updated 2 days ago", icon: "users" },
  { id: "first-project", collection: "getting-started", type: "Guide", title: "Create your first project", excerpt: "A short walkthrough for turning a blank workspace into a focused delivery plan.", read: "6 min read", updated: "Updated 1 week ago", icon: "plus" },
  { id: "project-status", collection: "workspace", type: "Best practice", title: "Keep project status meaningful", excerpt: "Use progress, updates, and ownership signals to help everyone see what matters.", read: "5 min read", updated: "Updated today", icon: "layers" },
  { id: "saved-views", collection: "workspace", type: "Guide", title: "Build and share saved views", excerpt: "Create repeatable views for launches, handoffs, risk reviews, and more.", read: "3 min read", updated: "Updated 4 days ago", icon: "layout" },
  { id: "invoices", collection: "account", type: "Reference", title: "Find invoices and manage payment details", excerpt: "Download past invoices, change your card, or update your billing contact.", read: "4 min read", updated: "Updated 5 days ago", icon: "file" },
  { id: "two-factor", collection: "security", type: "Guide", title: "Set up two-factor authentication", excerpt: "Add a second layer of protection to your Aster account in under two minutes.", read: "3 min read", updated: "Updated yesterday", icon: "lock" },
  { id: "webhooks", collection: "integrations", type: "Developer", title: "Listen for workspace events with webhooks", excerpt: "Subscribe to project, task, and membership events from your own service.", read: "8 min read", updated: "Updated 3 weeks ago", icon: "code" },
];

const faqs = [
  ["Can I change my workspace URL?", "Yes. Workspace admins can request a URL change from Account settings. Existing links are redirected for 30 days after the change."],
  ["What happens when a trial ends?", "Your workspace becomes read-only until a plan is selected. Your projects and files remain safely available for 30 days."],
  ["How do I export my project data?", "Open a project, choose Export from the actions menu, and select CSV or JSON. Larger exports are delivered by email."],
  ["Is there a status page for Aster?", "Yes. The service-status link in the footer shows live incident notes, scheduled maintenance, and historical uptime."],
];

function ArticleIcon({ icon }) {
  return <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-700 dark:bg-violet-950/70 dark:text-violet-300"><PageIcon name={icon} size={19} /></span>;
}

export default function HelpPage() {
  const [query, setQuery] = useState("");
  const [activeCollection, setActiveCollection] = useState("all");
  const [openFaq, setOpenFaq] = useState(null);
  const [selectedArticle, setSelectedArticle] = useState(null);
  const [chatOpen, setChatOpen] = useState(false);
  const [feedback, setFeedback] = useState("");

  const shownArticles = useMemo(() => {
    const search = query.trim().toLowerCase();
    return articles.filter((article) => (activeCollection === "all" || article.collection === activeCollection) && (!search || `${article.title} ${article.excerpt} ${article.type}`.toLowerCase().includes(search)));
  }, [activeCollection, query]);

  const chooseArticle = (article) => {
    setSelectedArticle(article);
    document.getElementById("documentation-reader")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <div id="help-documentation-page" className="mx-auto w-full max-w-7xl space-y-8 pb-12">
      <section className="relative overflow-hidden rounded-3xl bg-slate-950 px-5 py-9 text-white shadow-xl sm:px-8 sm:py-12">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_10%,rgba(139,92,246,.48),transparent_28%),radial-gradient(circle_at_20%_100%,rgba(34,211,238,.22),transparent_32%)]" />
        <div className="relative mx-auto max-w-3xl text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold text-violet-100 backdrop-blur"><PageIcon name="circleHelp" size={14} />Aster support center</span>
          <h1 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">How can we help?</h1>
          <p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-300 sm:text-base">Guides, answers, and practical playbooks to help your team get more value from every workspace.</p>
          <label className="relative mx-auto mt-6 block max-w-2xl text-left">
            <span className="sr-only">Search documentation</span>
            <PageIcon className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" name="search" size={19} />
            <input id="help-documentation-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search guides, billing, security, integrations…" className="w-full rounded-2xl border border-white/10 bg-white px-11 py-3.5 text-sm font-medium text-slate-900 shadow-lg outline-none transition placeholder:text-slate-400 focus:ring-4 focus:ring-violet-400/30" />
            {query && <button id="clear-help-search-button" onClick={() => setQuery("")} type="button" aria-label="Clear search" className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><PageIcon name="close" size={16} /></button>}
          </label>
          <div className="mt-4 flex flex-wrap justify-center gap-x-4 gap-y-2 text-xs text-slate-300"><span>Popular:</span><button type="button" onClick={() => setQuery("two-factor authentication")} className="font-semibold text-white hover:text-violet-200">two-factor auth</button><button type="button" onClick={() => setQuery("invoices")} className="font-semibold text-white hover:text-violet-200">invoices</button><button type="button" onClick={() => setQuery("webhooks")} className="font-semibold text-white hover:text-violet-200">webhooks</button></div>
        </div>
      </section>

      <section aria-label="Support shortcuts" className="grid gap-3 sm:grid-cols-3">
        {[{ id: "help-guides", icon: "book", title: "Browse guides", description: "Step-by-step help for every workflow.", action: () => document.getElementById("documentation-library")?.scrollIntoView({ behavior: "smooth" }) }, { id: "help-contact", icon: "message", title: "Contact support", description: "Talk to a real person when you’re stuck.", action: () => setChatOpen(true) }, { id: "help-status", icon: "clock", title: "Service status", description: "Live uptime and maintenance updates.", action: () => setFeedback("All systems are operational.") }].map((item) => <button key={item.id} id={item.id} type="button" onClick={item.action} className="group flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md dark:border-slate-800 dark:bg-slate-900 dark:hover:border-violet-700"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-700 transition group-hover:bg-violet-100 group-hover:text-violet-700 dark:bg-slate-800 dark:text-slate-200 dark:group-hover:bg-violet-950 dark:group-hover:text-violet-300"><PageIcon name={item.icon} size={19} /></span><span><span className="block text-sm font-semibold text-slate-900 dark:text-white">{item.title}</span><span className="mt-0.5 block text-xs leading-5 text-slate-500 dark:text-slate-400">{item.description}</span></span><PageIcon className="ml-auto text-slate-300 group-hover:text-violet-500 dark:text-slate-600" name="arrowRight" size={16} /></button>)}
      </section>

      <section id="documentation-library" className="grid gap-6 lg:grid-cols-[248px_minmax(0,1fr)]">
        <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-3 shadow-sm lg:sticky lg:top-5 dark:border-slate-800 dark:bg-slate-900">
          <p className="px-2 pb-2 pt-1 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Documentation</p>
          <button id="help-collection-all" type="button" onClick={() => setActiveCollection("all")} className={`flex w-full items-center gap-2 rounded-xl px-2.5 py-2 text-left text-sm font-medium transition ${activeCollection === "all" ? "bg-violet-50 text-violet-700 dark:bg-violet-950/70 dark:text-violet-300" : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><PageIcon name="book" size={16} />All articles<span className="ml-auto text-xs opacity-60">{articles.length}</span></button>
          <div className="mt-1 space-y-0.5">
            {collections.map((collection) => <button id={`help-collection-${collection.id}`} key={collection.id} type="button" onClick={() => setActiveCollection(collection.id)} className={`flex w-full items-center gap-2 rounded-xl px-2.5 py-2 text-left text-sm font-medium transition ${activeCollection === collection.id ? "bg-violet-50 text-violet-700 dark:bg-violet-950/70 dark:text-violet-300" : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><PageIcon name={collection.icon} size={16} />{collection.label}<span className="ml-auto text-xs opacity-60">{collection.count}</span></button>)}
          </div>
          <div className="mt-4 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><p className="text-xs font-semibold text-slate-700 dark:text-slate-200">Developer resources</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Build against our event-ready test surfaces.</p><a href="#developer-resources" className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-violet-700 hover:text-violet-900 dark:text-violet-300"><PageIcon name="code" size={13} />View API docs</a></div>
        </aside>

        <div>
          <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
            <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-600 dark:text-violet-400">{activeCollection === "all" ? "Knowledge base" : collections.find((item) => item.id === activeCollection)?.label}</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-950 dark:text-white">{query ? `Results for “${query}”` : "Browse helpful articles"}</h2></div>
            <span className="text-sm text-slate-500 dark:text-slate-400">{shownArticles.length} article{shownArticles.length === 1 ? "" : "s"}</span>
          </div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            {shownArticles.map((article) => <button id={`help-article-${article.id}`} key={article.id} onClick={() => chooseArticle(article)} type="button" className="group flex min-h-44 flex-col rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md dark:border-slate-800 dark:bg-slate-900 dark:hover:border-violet-700"><div className="flex items-start gap-3"><ArticleIcon icon={article.icon} /><div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-wide text-violet-600 dark:text-violet-400">{article.type}</p><h3 className="mt-1 text-sm font-semibold leading-5 text-slate-900 dark:text-white">{article.title}</h3></div></div><p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">{article.excerpt}</p><span className="mt-auto flex items-center justify-between pt-3 text-[11px] text-slate-400"><span>{article.read}</span><span className="inline-flex items-center gap-1 font-semibold text-violet-700 opacity-0 transition group-hover:opacity-100 dark:text-violet-300">Read guide <PageIcon name="arrowRight" size={13} /></span></span></button>)}
          </div>
          {!shownArticles.length && <div id="help-empty-search-state" className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-5 py-12 text-center dark:border-slate-700 dark:bg-slate-900"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-slate-400 shadow-sm dark:bg-slate-800"><PageIcon name="search" size={20} /></span><h3 className="mt-4 text-sm font-semibold text-slate-900 dark:text-white">No guides match that search</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Try a different phrase, or get in touch with our support team.</p><button type="button" onClick={() => { setQuery(""); setActiveCollection("all"); }} className="mt-4 text-xs font-semibold text-violet-700 hover:text-violet-900 dark:text-violet-300">Clear filters</button></div>}
        </div>
      </section>

      {selectedArticle && <section id="documentation-reader" className="scroll-mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="flex gap-4"><ArticleIcon icon={selectedArticle.icon} /><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-violet-600 dark:text-violet-400">{selectedArticle.type}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">{selectedArticle.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{selectedArticle.excerpt}</p></div></div><button id="close-documentation-reader" type="button" onClick={() => setSelectedArticle(null)} aria-label="Close article" className="h-fit rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800 dark:hover:text-white"><PageIcon name="close" size={19} /></button></div><div className="mt-6 grid gap-5 border-t border-slate-100 pt-5 dark:border-slate-800 md:grid-cols-[1fr_220px]"><div className="space-y-4 text-sm leading-7 text-slate-600 dark:text-slate-300"><p>Start by opening the relevant workspace area and confirming that you have the right permissions. Nimbus saves changes as you go, so your team can follow along in real time.</p><div className="rounded-xl border border-violet-100 bg-violet-50 p-4 text-sm text-violet-900 dark:border-violet-900/60 dark:bg-violet-950/40 dark:text-violet-100"><strong className="font-semibold">Helpful tip:</strong> use the activity panel whenever you want to confirm a change has reached everyone on the team.</div><p>Once the setup is complete, invite collaborators, review the shared status, and pin the view your team will use most often. The result is a workspace that stays clear even as work changes.</p></div><aside className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><p className="text-xs font-semibold text-slate-800 dark:text-white">Was this helpful?</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Your feedback improves our docs.</p><div className="mt-3 flex gap-2"><button id="documentation-feedback-positive" type="button" onClick={() => setFeedback("Thanks — this article was marked helpful.")} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-500 transition hover:border-emerald-300 hover:text-emerald-600 dark:border-slate-700 dark:bg-slate-900"><PageIcon name="thumbsUp" size={16} /></button><button id="documentation-feedback-negative" type="button" onClick={() => setFeedback("Thanks — we’ll use this feedback to improve the guide.")} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-500 transition hover:border-rose-300 hover:text-rose-600 dark:border-slate-700 dark:bg-slate-900"><PageIcon name="thumbsDown" size={16} /></button></div></aside></div></section>}

      <section id="developer-resources" className="rounded-3xl border border-cyan-100 bg-gradient-to-br from-cyan-50 to-violet-50 p-5 dark:border-cyan-900/50 dark:from-cyan-950/30 dark:to-violet-950/30 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-cyan-300 shadow-lg"><PageIcon name="code" size={20} /></span><div><h2 className="text-lg font-semibold text-slate-950 dark:text-white">Building with Nimbus?</h2><p className="mt-1 max-w-xl text-sm leading-6 text-slate-600 dark:text-slate-300">Explore event payloads, API patterns, and iframe-friendly example projects for your test workspace.</p></div></div><a id="documentation-api-reference-link" href="/embedded-content#embed-origin" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-slate-800 dark:bg-white dark:text-slate-950"><PageIcon name="code" size={16} />Explore examples</a></div></section>

      <section className="grid gap-6 lg:grid-cols-[1fr_0.8fr]">
        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-600 dark:text-violet-400">Common questions</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-950 dark:text-white">A few quick answers</h2><div className="mt-4 divide-y divide-slate-100 rounded-2xl border border-slate-200 px-4 dark:divide-slate-800 dark:border-slate-800">{faqs.map(([question, answer], index) => <div key={question}><button id={`help-faq-${index + 1}`} type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} className="flex w-full items-center justify-between gap-4 py-4 text-left text-sm font-semibold text-slate-800 dark:text-slate-100"><span>{question}</span><PageIcon className={`shrink-0 text-violet-600 transition ${openFaq === index ? "rotate-180" : ""}`} name="chevronDown" size={17} /></button>{openFaq === index && <p id={`help-faq-answer-${index + 1}`} className="-mt-1 pb-4 text-sm leading-6 text-slate-500 dark:text-slate-400">{answer}</p>}</div>)}</div></div>
        <aside className="relative overflow-hidden rounded-3xl bg-violet-600 p-6 text-white shadow-lg"><div className="absolute -right-7 -top-7 h-32 w-32 rounded-full bg-cyan-300/25 blur-2xl" /><div className="relative"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/15 text-white"><PageIcon name="message" size={19} /></span><h2 className="mt-5 text-xl font-semibold tracking-tight">Still need a hand?</h2><p className="mt-2 text-sm leading-6 text-violet-100">Our support team typically replies in under two business hours.</p><button id="open-help-chat-button" type="button" onClick={() => setChatOpen(true)} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-violet-700 shadow-sm transition hover:bg-violet-50"><PageIcon name="message" size={16} />Start a conversation</button><a id="help-contact-page-link" href="/contact" className="mt-3 block text-xs font-semibold text-violet-100 hover:text-white">Or send a detailed request →</a></div></aside>
      </section>

      {chatOpen && <div id="help-chat-widget" role="dialog" aria-modal="true" aria-labelledby="help-chat-title" className="fixed bottom-5 right-5 z-50 w-[calc(100%-2.5rem)] max-w-sm overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between bg-slate-950 px-4 py-3 text-white"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-violet-500"><PageIcon name="message" size={14} /></span><div><p id="help-chat-title" className="text-sm font-semibold">Nimbus Support</p><p className="text-[10px] text-emerald-300">● Usually replies in 2 hours</p></div></div><button id="close-help-chat-button" type="button" onClick={() => setChatOpen(false)} aria-label="Close chat" className="rounded-lg p-1 text-slate-300 hover:bg-white/10 hover:text-white"><PageIcon name="close" size={17} /></button></div><div className="h-52 space-y-3 bg-slate-50 p-4 dark:bg-slate-950"><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-white p-3 text-xs leading-5 text-slate-600 shadow-sm dark:bg-slate-800 dark:text-slate-300">Hi! I’m Nova. What can we help you accomplish today?</div>{feedback && <div className="ml-auto max-w-[85%] rounded-2xl rounded-tr-sm bg-violet-600 p-3 text-xs leading-5 text-white">{feedback}</div>}</div><form onSubmit={(event) => { event.preventDefault(); setFeedback("Thanks! A support specialist will follow up shortly."); }} className="flex gap-2 border-t border-slate-100 p-3 dark:border-slate-800"><input id="help-chat-input" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 dark:border-slate-700 dark:bg-slate-950 dark:text-white" placeholder="Write a message…" /><button id="help-chat-send-button" type="submit" className="rounded-xl bg-violet-600 px-3 text-white hover:bg-violet-700"><PageIcon name="send" size={15} /></button></form></div>}
      {feedback && !chatOpen && <div id="help-feedback-toast" role="status" className="fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-medium text-white shadow-xl"><PageIcon className="text-emerald-300" name="checkCircle" size={17} />{feedback}<button onClick={() => setFeedback("")} type="button" aria-label="Dismiss message" className="ml-auto text-slate-400 hover:text-white"><PageIcon name="close" size={16} /></button></div>}
    </div>
  );
}
